ROADSHOW_DEMO_CODE = (
    "#include <memory>\n"
    "#include <optional>\n"
    "#include <variant>\n"
    "#include <vector>\n"
    "using namespace std;\n"
    "struct Node { int value; Node* next; };\n"
    "class Animal { public: int age; virtual int speak() { return age; } virtual ~Animal() {} };\n"
    "class Dog : public Animal { public: int bones; Dog(int a, int b) { age = a; bones = b; } int speak() override { return age + bones; } };\n"
    "int total = 42;\n"
    "int* focus = &total;\n"
    "*focus = 52;\n"
    "Node first{1, nullptr};\n"
    "Node second{2, &first};\n"
    "second.next->value = 5;\n"
    "vector<unique_ptr<Node>> nodes;\n"
    "nodes.push_back(make_unique<Node>(Node{3, &second}));\n"
    "nodes[0]->next->next->value = 8;\n"
    "unique_ptr<Animal> pet = make_unique<Dog>(4, 6);\n"
    "int sound = pet->speak();\n"
    "optional<Node> maybe = Node{7, &first};\n"
    "maybe->next->value = 9;\n"
    "variant<int, Node> either = Node{10, &second};\n"
    "int done = first.value + second.value + sound;\n"
)
